const ADD = "ADD";
const DELETE = "DELETE";
const UPDATE_TASK_STATE = "UPDATE_TASK_STATE";
const UPDATE_TASK_DATA = "UPDATE_TASK_DATA";

const DEFAULT_VISIBILITY = "ALL";
const DONE_VISIBILITY = "TRUE";
const NOT_DONE_VISIBILITY = "FALSE";
const UPDATE_VISIBILITY_FILTER = "UPDATE_VISIBILITY_FILTER";
const EDIT_MODAL_VISIBILITY_FILTER = "EDIT_MODAL_VISIBILITY_FILTER";

export {
  ADD,
  DELETE,
  UPDATE_TASK_DATA,
  UPDATE_TASK_STATE,
  DEFAULT_VISIBILITY,
  DONE_VISIBILITY,
  NOT_DONE_VISIBILITY,
  UPDATE_VISIBILITY_FILTER,
  EDIT_MODAL_VISIBILITY_FILTER,
};
